<?php
/**
 * Admin view for the History page.
 *
 * @package Catapulte-Autoplugin
 * @since 2.1.0
 */

namespace Catapulte_Autoplugin;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$history_list_table = new Admin\History_List_Table();
$history_list_table->prepare_items();
$no_entries = empty( $history_list_table->items );

?>
<div class="wrap">
	<h1>
		<?php esc_html_e( 'Generation History', 'catapulte-autoplugin' ); ?>
		<a href="<?php echo esc_url( admin_url( 'admin.php?page=catapulte-autoplugin-generate' ) ); ?>" class="page-title-action"><?php esc_html_e( 'Generate New Plugin', 'catapulte-autoplugin' ); ?></a>
	</h1>

	<p class="description">
		<?php esc_html_e( 'View the history of all plugins generated by Catapulte-Autoplugin. You can view the original specifications and regenerate plugins if needed.', 'catapulte-autoplugin' ); ?>
	</p>

	<?php if ( $no_entries ) : ?>
		<div class="catapulte-autoplugin-card">
			<h2><?php esc_html_e( 'No history entries yet.', 'catapulte-autoplugin' ); ?></h2>
			<p><?php esc_html_e( 'When you generate plugins, they will appear here so you can view and modify them later.', 'catapulte-autoplugin' ); ?></p>
			<a href="<?php echo esc_url( admin_url( 'admin.php?page=catapulte-autoplugin-generate' ) ); ?>" class="button button-primary button-hero"><?php esc_html_e( 'Generate Your First Plugin', 'catapulte-autoplugin' ); ?></a>
		</div>
	<?php else : ?>
		<form method="get">
			<input type="hidden" name="page" value="catapulte-autoplugin-history" />
			<?php
			$history_list_table->search_box( __( 'Search History', 'catapulte-autoplugin' ), 'history' );
			$history_list_table->display();
			?>
		</form>
	<?php endif; ?>
</div>
